### ISSUE TITLE
Issue with ACACIA_PRESSURE_PLATE

### ISSUE THREAD

**Issue by Warbat** [eccentricdevotion/DiscoverWarps#5]
A problem I am encountering with Discover Warps 1.6 while on a 1.12.2 build bukkit server. These seems to be the same issue with and without WorldGuard. The plugin has an issue with something about ACACIA_PRESSURE_PLATE.

[05:14:27] [Server thread/INFO]: Starting minecraft server version 1.12.2
[05:14:27] [Server thread/INFO]: Loading properties
[05:14:27] [Server thread/INFO]: Default game type: SURVIVAL
[05:14:27] [Server thread/INFO]: Generating keypair
[05:14:28] [Server thread/INFO]: Starting Minecraft server on *:25575
[05:14:28] [Server thread/INFO]: Using default channel type
[05:14:29] [Server thread/INFO]: This server is running CraftBukkit version git-Bukkit-8166d17 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)
[05:14:29] [Server thread/INFO]: [DiscoverWarps] Loading DiscoverWarps v1.6
[05:14:29] [Server thread/INFO]: Preparing level "world"
[05:14:30] [Server thread/INFO]: Preparing start region for level 0 (Seed: 300921943514321883)
[05:14:31] [Server thread/INFO]: Preparing spawn area: 0%
[05:14:32] [Server thread/INFO]: Preparing spawn area: 36%
[05:14:33] [Server thread/INFO]: Preparing spawn area: 79%
[05:14:34] [Server thread/INFO]: Preparing start region for level 1 (Seed: 300921943514321883)
[05:14:35] [Server thread/INFO]: Preparing spawn area: 33%
[05:14:36] [Server thread/INFO]: Preparing spawn area: 64%
[05:14:37] [Server thread/INFO]: Preparing spawn area: 95%
[05:14:37] [Server thread/INFO]: Preparing start region for level 2 (Seed: 300921943514321883)
[05:14:37] [Server thread/INFO]: [DiscoverWarps] Enabling DiscoverWarps v1.6
[05:14:37] [Server thread/ERROR]: Error occurred while enabling DiscoverWarps v1.6 (Is it up to date?)
java.lang.NoSuchFieldError: ACACIA_PRESSURE_PLATE
	at me.eccentric_nz.discoverwarps.DiscoverWarpsCommands.<init>(DiscoverWarpsCommands.java:49) ~[?:?]
	at me.eccentric_nz.discoverwarps.DiscoverWarps.onEnable(DiscoverWarps.java:65) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[craftbukkit-1.12.2.jar:git-Bukkit-8166d17]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:329) [craftbukkit-1.12.2.jar:git-Bukkit-8166d17]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:402) [craftbukkit-1.12.2.jar:git-Bukkit-8166d17]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:367) [craftbukkit-1.12.2.jar:git-Bukkit-8166d17]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:328) [craftbukkit-1.12.2.jar:git-Bukkit-8166d17]
	at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:412) [craftbukkit-1.12.2.jar:git-Bukkit-8166d17]
	at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:373) [craftbukkit-1.12.2.jar:git-Bukkit-8166d17]
	at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:328) [craftbukkit-1.12.2.jar:git-Bukkit-8166d17]
	at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:248) [craftbukkit-1.12.2.jar:git-Bukkit-8166d17]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:522) [craftbukkit-1.12.2.jar:git-Bukkit-8166d17]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_91]
[05:14:37] [Server thread/INFO]: Server permissions file permissions.yml is empty, ignoring it
[05:14:37] [Server thread/INFO]: Done (8.517s)! For help, type "help" or "?"

**Comment by Warbat** [comment]
Oh, and following this happening, the only response from the plugin regardless of command is as follows

[05:18:53] [Server thread/INFO]: type /dw to see help...[m
[05:18:56] [Server thread/INFO]: type /dw to see help...[m
[05:18:59] [Server thread/INFO]: type /dw to see help...[m
[05:18:59] [Server thread/INFO]: type /dw to see help...[m
[05:19:00] [Server thread/INFO]: type /dw to see help...[m
 the plugin also does not function to protect previous version's placed warps, as I attempted in one instance to set a warp with 1.5.3 (which works to create warps, but with expected errors due to outdating) then replaced 1.5.3 with 1.6, received the error about the pressure plate, and it was no longer protected. Perhaps this particular event is to be expected since it was created by a previous version of DiscoverWarps, but I thought I would make mention as I did include it in my round of testing for a workaround.

**Comment by eccentricdevotion** [comment]
v1.6 is for Minecraft/Spigot 1.13.x
